### ISSUE TITLE
Array of members duplicates if "about" page is clicked multiple times

### ISSUE THREAD

**Issue by jadebuckwalter** [tektaxi/BLBB#5]
If the user is already on the about page and they click on it again, the array of members is cloned again. This may be an ongoing problem with using "hide/show" pages...

**Comment by tektaxi** [comment]
could we run the function once when the page loads? instead of running it each time the about tab is clicked

**Comment by tektaxi** [comment]
So I was able to fix this in 2482e95. I switched the function to run based on an event listener, instead of using `onclick` in the HTML. This way we can remove the event listener after it gets called once, therefore only loading the members one time.
