### ISSUE TITLE
About page card styling

### ISSUE THREAD

**Issue by tektaxi** [tektaxi/BLBB#7]
Right now, we just use one bootstrap class in the 'members' card template. Personally, I kind of like the full default bootstrap styles for the cards, like I used on my site (pic below). Not a big deal or anything, but adding that styling could be cool? @jadebuckwalter what do you think?

<img width="356" alt="Screen Shot 2021-01-03 at 12 59 55 AM" src="https://user-images.githubusercontent.com/45189395/103472745-02415500-4d5f-11eb-86c2-a0e0226714f1.png">

**Comment by jadebuckwalter** [comment]
@tektaxi Definitely! I just did the bare minimum with styling to get the cards on the page.
